version: 2.1

executors:
  lineage-docker:
    docker:
      - image: cimg/ubuntu:22.04
    resource_class: large

jobs:
  build:
    executor: lineage-docker
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              openjdk-17-jdk git git-lfs curl wget bc bison build-essential \
              ccache flex gperf libncurses5-dev libssl-dev libxml2-utils \
              lzop python3 rsync unzip zip zlib1g-dev liblz4-tool aria2 \
              gnupg file repo
            git lfs install
      - restore_cache:
          keys:
            - ccache-{{ .Branch }}
      - run:
          name: Run build script
          command: |
            chmod +x build.sh
            ./build.sh
      - save_cache:
          key: ccache-{{ .Branch }}
          paths:
            - ~/.ccache
      - store_artifacts:
          path: ~/artifacts
          destination: cannong-build

workflows:
  build-workflow:
    jobs:
      - build


